Repository 2008-Untangled/Untangled-FE, pull requests merged in 2021-03, with the labels that each got.

#22 Feature/display memories
  src/App/App.js
  src/Memory/Memory.js
  src/Overview/Overview.js
  src/Room/Room.js
  src/UI/Modal.js
Labels: React/Component, Styles, data display, enhancement

#28 Feature update memories form
  assets/SVGs/noun_Thinking_1774494.svg
  assets/SVGs/noun_edit_2216543.svg
  assets/room-images/livingroom.png
  src/Memory/Memory.js
  src/MemoryForm/MemoryForm.js
  src/apiCalls.js
Labels: React/Component, Styles, apiCalls, data display, enhancement

#31 Modal styling
  assets/logolarge.png
  assets/logomedium.png
  assets/logosmall.png
  src/HomePage/HomePage.js
  src/Memory/Memory.js
  src/MemoryForm/MemoryForm.js
  src/Overview/Overview.js
  src/Room/Room.js
Labels: Styles, enhancement

#32 Testing
  package-lock.json
  package.json
  src/HomePage/HomePage.js
  src/HomePage/HomePage.test.js
  src/Memory/Memory.js
  src/Overview/Overview.test.js
  src/Room/Room.js
  src/Room/Room.test.js
Labels: React/Testing, Self Education, apiCalls, enhancement

#33 Feature back for form
  assets/thoughtBubble.png
  src/Memory/Memory.js
  src/MemoryForm/MemoryForm.js
  src/Room/Room.js
Labels: Styles, enhancement

#35 Feature/delete memory
  src/Memory/Memory.js
  src/MemoryForm/MemoryForm.js
  src/Room/Room.js
  src/apiCalls.js
Labels: apiCalls, enhancement
