Repository 2008-Untangled/Untangled-FE, pull requests merged in 2021-02, with the labels that each got.

#14 Add HomePage component setup
  package-lock.json
  src/App/App.js
  src/HomePage/HomePage.js
Labels: React/Component, enhancement

#15 Feature/memory component
  src/Memory/Memory.js
Labels: React/Component, data display, enhancement

#16 Create room component
  assets/room-images/livingroom.png
  package-lock.json
  package.json
  src/App/App.js
  src/Room/Room.js
  src/Stack/Stack.js
  src/UI/Button.js
Labels: React/Component, enhancement

#17 Create new folder and add backdrop files
  assets/backdrops/bedroom.png
  assets/backdrops/homefront.png
  assets/backdrops/kitchen.png
  assets/backdrops/livingroom.png
Labels: Styles, enhancement

#18 Add function definitions for api calls
  src/apiCalls.js
Labels: apiCalls, enhancement

#19 Feature/navigation initial
  package-lock.json
  src/App/App.js
  src/HomePage/HomePage.js
  src/Memory/Memory.js
  src/Overview/Overview.js
  src/Room/Room.js
  src/Stack/Stack.js
  src/UI/Button.js
Labels: React/Component, apiCalls, data display

#20 Feature/overview style
  src/Overview/Overview.js
  src/Room/Room.js
Labels: enhancement

#21 Brand styles room component
  assets/brandColors.js
  src/HomePage/HomePage.js
  src/Memory/Memory.js
  src/Overview/Overview.js
  src/Room/Room.js
  src/apiCalls.js
Labels: React/Component, apiCalls, enhancement
